/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.EditorRole;

import Business.AccountPackage.Account;
import Business.ManagementEnterprise;
import Business.NetworkPackage.Network;
import Business.NewsGroupPackage.NewsGroup;
import Business.OrgPackage.DirectorOrganization;
import Business.Organization;
import Business.WorkPackage.EDWork;
import Business.WorkPackage.JEWork;
import java.awt.CardLayout;
import java.awt.Component;
import java.io.File;
import javax.swing.JPanel;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author sheldon
 */
public class EditoralWorkPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    ManagementEnterprise enterprise;
    JEWork JErequest;
    Account account;
    NewsGroup business;
    File file;
    String reportpath;

    /**
     * Creates new form EditoralWorkPanel
     * @param userProcessContainer
     * @param account
     * @param request
     * @param business
     */
    public EditoralWorkPanel(JPanel userProcessContainer, Account account,JEWork request, NewsGroup business) {
        initComponents();
        this.setSize(970,620);
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.account = account;
        this.JErequest = request;
        this.business = business;
        reportpath = request.getReportContent();
        
        ReportTitleTextField.setText(request.getReportTitle());
        if (request.getReportContent() != null){
            try {
                ReportTextArea.read(new FileReader(reportpath), null);
                
            } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "problem accessing file");
            }
        } else {
        JOptionPane.showMessageDialog(null, "File access cancelled by user.");
        }
        ReportTitleTextField.setEnabled(false);
        ReportTextArea.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        EditorialTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        submitJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ReportTitleTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        EditorialTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        ReportTextArea = new javax.swing.JTextArea();
        uploadButton = new javax.swing.JButton();

        setOpaque(false);

        EditorialTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        backJButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        submitJButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        submitJButton.setText("Submit Editoral");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Editorial Title:");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("Report Title:");

        ReportTitleTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        EditorialTextArea.setColumns(20);
        EditorialTextArea.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        EditorialTextArea.setRows(5);
        jScrollPane1.setViewportView(EditorialTextArea);

        ReportTextArea.setColumns(20);
        ReportTextArea.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        ReportTextArea.setRows(5);
        jScrollPane2.setViewportView(ReportTextArea);

        uploadButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        uploadButton.setText("Upload Editorial");
        uploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(uploadButton)
                        .addGap(30, 30, 30)
                        .addComponent(submitJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(ReportTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(EditorialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ReportTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(EditorialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton)
                    .addComponent(uploadButton)
                    .addComponent(submitJButton))
                .addGap(61, 61, 61))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        EditorWorkPanel dwjp = (EditorWorkPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed

        //submit only once
  
        if (file != null && !"".equals(EditorialTextField.getText())){ 
            //couldn't be submitted, if title is blank
            String editorialpath = file.getAbsolutePath();
            
            JErequest.setEditorialTitle(EditorialTextField.getText());
            JErequest.setStatus("Completed");
            
            EDWork EDrequest = new EDWork();
            EDrequest.setReportTitle(JErequest.getReportTitle());
            EDrequest.setReportContent(reportpath);
            
            EDrequest.setSender(JErequest.getReceiver());
            EDrequest.setStatus("Sent");
            
            EDrequest.setEditorialTitle(EditorialTextField.getText());
            EDrequest.setEditorialContent(editorialpath);
            EDrequest.setApprove(false);
            EDrequest.setJeWork(JErequest);
        
            Network nn = null;
            //for(Network i : NewsGroup.getInstance().getNetworkList()){
            for(Network i : business.getNetworkList()){
                if(i.getType().equals("Management")){
                    nn = i;
                    break;
                }
            }
            for (ManagementEnterprise b : nn.getManagementDirectory().getEnterpriseList()){
                Organization org = null;
                for (Organization organization : b.getOrganizationDirectory().getOrganizationList()){
                //String s = organization.getName();
                if (organization instanceof DirectorOrganization){
                    org = organization;
                    break;
                }
            }
                if (org!=null){
                    org.getWorkQueue().getWorkRequestList().add(EDrequest);
                    account.getWorkQueue().getWorkRequestList().add(EDrequest);
                }
            }
            JOptionPane.showMessageDialog(null, "Editorial Submitted!");
            EditorialTextArea.setEnabled(false);
            EditorialTextField.setEnabled(false);
            submitJButton.setEnabled(false);
            uploadButton.setEnabled(false);
            
        } else if (file == null && EditorialTextField.getText().equals("")) JOptionPane.showMessageDialog(null, "No work submit!");
        else if (EditorialTextField.getText().equals(""))JOptionPane.showMessageDialog(null, "Please write your title!");
        else if (file == null)JOptionPane.showMessageDialog(null, "Please select a file!");
        
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void uploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadButtonActionPerformed
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
        file = fileChooser.getSelectedFile();
        try {
          EditorialTextArea.read( new FileReader( file.getAbsolutePath() ), null );
          JOptionPane.showMessageDialog(null,"Upload success");
        } catch (IOException ex) {
          JOptionPane.showMessageDialog(null, "problem accessing file"+file.getAbsolutePath());
        }
        } else {
        JOptionPane.showMessageDialog(null, "File access cancelled by user.");
    }
    }//GEN-LAST:event_uploadButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea EditorialTextArea;
    private javax.swing.JTextField EditorialTextField;
    private javax.swing.JTextArea ReportTextArea;
    private javax.swing.JTextField ReportTitleTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton submitJButton;
    private javax.swing.JButton uploadButton;
    // End of variables declaration//GEN-END:variables
}
